# Generated by Django 2.0.7 on 2018-07-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('img', models.FileField(upload_to='img/')),
            ],
        ),
    ]
